### ISSUE TITLE
problem with python

### ISSUE THREAD

**Issue by julian811** [LionelDarras/PyVantagePro#2]
Hello, I'm Julian, I use pyvantagepro and it's very usefull. But when I want to use it with python I have an error when I write it :
>>> device = VantagePro2.from_url('/dev/ttyUSB0:19200:8N1')

The error is :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyVantagePro-0.3.2-py2.7.egg/pyvantagepro/device.py", line 78, in from_url
    link = link_from_url(url)
  File "/usr/local/lib/python2.7/dist-packages/PyLink-0.3.2-py2.7.egg/pylink/__init__.py", line 57, in link_from_url
    raise ValueError('Bad url link sepecified')
ValueError: Bad url link sepecified

And I don't know what is the problem because I've done what you have written.
Can you help me please ?

Goodbye

Julian

**Comment by JernejJerin** [comment]
You have not specified correct URL where your Vantage Pro2 is available. Check [PyLink](https://github.com/LionelDarras/PyLink) for examples on how to specify URL for different types of communication ports used (RS232, USB, etc.). Can you specify, how is your console connected to your computer, is it via RS232 or USB?

**Comment by julian811** [comment]
I'm sorry I worked late and I solved my problem and I haven't had the time to tell you.

But think you for your quick answer.


Good evening,


Julian


Télécharger Outlook pour Android






On Wed, May 25, 2016 at 10:06 AM -0700, "Jernej Jerin" <notifications@github.com> wrote:





You have not specified correct URL where your Vantage Pro2 is available. Check [PyLink](https://github.com/LionelDarras/PyLink) for examples on how to specify URL for different types of communication ports used (RS232, USB, etc.). Can you specify, how is your console connected to your computer, is it via RS232 or USB?

---

**Comment by LionelDarras** [comment]
Hi,
Thanks a lot for using PyVantagePro.
I see your issue today and i see it's solved ! Cool !
I will try to write a documentation more precise for pylink like it was done for PyVantagePro.

Best Regards.
Lionel Darras
